# Generated by Django 6.0.6 on 2026-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authsession',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
