# Generated by Django 6.0.6 on 2026-07-19 12:43

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authsession_ip_address_authsession_user_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='authidentity',
            name='email',
            field=accounts.models.CaseInsensitiveEmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=accounts.models.CaseInsensitiveEmailField(max_length=254, unique=True),
        ),
    ]
