# Generated by Django 6.0.6 on 2026-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
